name: Release Artifacts
on:
  push:
    tags:
      - '*'
jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'
      - name: Install Deps
        run: pip install -U twine wheel
      - name: Build Artifacts
        run: |
          python setup.py sdist
          python setup.py bdist_wheel
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/qiskit*
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
